/**
 * Ensures placeholder symbol/color PNGs exist when missing, samples Colors.png
 * into src/projects/set-dojo/generated-colors.css (three stripes left-to-right).
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, '..', '..', '..');
const symbolsDir = path.join(root, 'public', 'projects', 'set-dojo', 'assets', 'symbols');
const setSymbolsPath = path.join(symbolsDir, 'SetSymbols.png');
const colorsPath = path.join(symbolsDir, 'Colors.png');
const generatedCssPath = path.join(root, 'src', 'projects', 'set-dojo', 'generated-colors.css');

const DEFAULT_COLORS = ['#d95b7a', '#33b579', '#7f6bff'];

function ensureDir(dir) {
  fs.mkdirSync(dir, { recursive: true });
}

async function ensurePlaceholderSetSymbols() {
  if (fs.existsSync(setSymbolsPath)) return;

  const cell = 96;
  const grid = cell * 3;
  const rects = [];
  for (let row = 0; row < 3; row += 1) {
    for (let col = 0; col < 3; col += 1) {
      const x = col * cell + 18;
      const y = row * cell + 18;
      rects.push(`<rect x="${x}" y="${y}" width="${cell - 36}" height="${cell - 36}" rx="14" fill="white"/>`);
    }
  }

  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${grid}" height="${grid}" viewBox="0 0 ${grid} ${grid}">
${rects.join('\n')}
</svg>`;

  await sharp(Buffer.from(svg)).png().toFile(setSymbolsPath);
  // eslint-disable-next-line no-console -- build script
  console.warn('[generate-set-dojo] Created placeholder SetSymbols.png — replace with your artwork.');
}

async function ensurePlaceholderColors() {
  if (fs.existsSync(colorsPath)) return;

  const w = 360;
  const h = 120;
  const band = w / 3;
  const rects = DEFAULT_COLORS.map((hex, index) => {
    const x = Math.round(index * band);
    return `<rect x="${x}" y="0" width="${Math.ceil(band)}" height="${h}" fill="${hex}"/>`;
  });

  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}">
${rects.join('\n')}
</svg>`;

  await sharp(Buffer.from(svg)).png().toFile(colorsPath);
  // eslint-disable-next-line no-console -- build script
  console.warn('[generate-set-dojo] Created placeholder Colors.png — replace with your palette.');
}

async function sampleColorsToCss() {
  await ensureDir(symbolsDir);
  await ensurePlaceholderColors();

  const { data, info } = await sharp(colorsPath).ensureAlpha().raw().toBuffer({ resolveWithObject: true });

  const width = info.width;
  const height = info.height;
  const channels = info.channels;
  const samples = [];

  for (let index = 0; index < 3; index += 1) {
    const bandLeft = Math.floor((index * width) / 3);
    const bandRight = Math.floor(((index + 1) * width) / 3);
    const cx = Math.floor((bandLeft + bandRight) / 2);
    const cy = Math.floor(height / 2);
    const pixelIndex = (cy * width + cx) * channels;
    const r = data[pixelIndex];
    const g = data[pixelIndex + 1];
    const b = data[pixelIndex + 2];
    const hex = `#${[r, g, b].map((channel) => channel.toString(16).padStart(2, '0')).join('')}`;
    samples.push(hex);
  }

  const css = `/* Generated by scripts/projects/set-dojo/generate-assets.mjs — do not edit by hand */
.set-dojo {
  --set-color-0: ${samples[0]};
  --set-color-1: ${samples[1]};
  --set-color-2: ${samples[2]};
}
`;

  ensureDir(path.dirname(generatedCssPath));
  fs.writeFileSync(generatedCssPath, css, 'utf8');
}

async function main() {
  ensureDir(symbolsDir);
  await ensurePlaceholderSetSymbols();
  await sampleColorsToCss();
}

await main();
